### ISSUE TITLE
Needs backwards-compat

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#10]
---------------------------------------
- Bitbucket: https://bitbucket.org/tommorris/mf2py/issue/8
- Originally Reported By: [Tom Morris](http://bitbucket.org/tommorris)
- Originally Created At: 2013-11-07T00:40:02.386

**Comment by kylewm** [comment]
ported backward compatibility classes from php-mf2 2014-05-03 9e2c8353d55096946ea7522751bf251a7f3bdd5c
