### ISSUE TITLE
Pip install results in wrong Beautiful Soup version

### ISSUE THREAD

**Issue by tallus** [tommorris/mf2py#15]
requires.txt lists:
BeautifulSoup
which results in BeautifulSoup==3.2.1
It should say __BeautifulSoup4__ per requirements.txt:
BeautifulSoup4==4.3.2

**Comment by kylewm** [comment]
This is fixed in the repo, still need to upload a new version to pypi

**Comment by kylewm** [comment]
This should be fixed starting with 0.2.2 https://pypi.python.org/pypi/mf2py/0.2.2

Thanks for reporting, @tallus!
