### ISSUE TITLE
turn on Travis-CI tests

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#29]
I enabled travis-CI builds on my fork a long time ago, it's really nice to get a report if a commit/branch/pull request breaks the build for any version of Python {2.6, 2.7, 3.3}. Totally up to you if you want to enable it, but I like it a lot.

Here's an example report https://travis-ci.org/kylewm/mf2py/builds/47810611

**Comment by tommorris** [comment]
I did this a while back. Closing this up.
