### ISSUE TITLE
Needs to parse u- properties

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#3]
---------------------------------------
- Bitbucket: https://bitbucket.org/tommorris/mf2py/issue/1
- Originally Reported By: [Tom Morris](http://bitbucket.org/tommorris)
- Originally Created At: 2013-11-07T00:35:52.765

**Comment by kylewm** [comment]
added 2013-11-07 a4630994c4f0d34f969ceb3d6957c80160648571 and a3b2a8566b69af58cac40c40b999f6a7d7526c40
