### ISSUE TITLE
add parse convenience method

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#31]
95% of the time when I use mf2py, I call `mf2py.Parser(...).to_dict()`. I would like to add a convenience method `parse` so that I can call `mf2py.parse(...)` and get the same result.

This is in the vein of python-requests, where the most common use cases can be handled with `requests.get` and `requests.post` but you can always create your own `requests.Request` object to do the complex stuff.

Thoughts? @tommorris @kartikprabhu

**Comment by tommorris** [comment]
That seems eminently reasonable.

**Comment by kartikprabhu** [comment]
sure go for it

**Comment by kylewm** [comment]
added in 3e0c268981ebdd72dd43408d5e0356ea36e9244f
