### ISSUE TITLE
parse u-* properties from link elements

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#33]
http://microformats.org/wiki/microformats2-parsing-issues#link_elements_and_u-_parsing

**Comment by tommorris** [comment]
:+1: I heartily approve.

**Comment by tantek** [comment]
Real world example now deployed: https://kylewm.com/services/mf2?url=http%3A%2F%2Ftantek.com%2Fcontact

result: couple of empty values in photo and url properties
expected result: those empty values have the appropriate http: URLs
