### ISSUE TITLE
timezone Z becomes +0000

### ISSUE THREAD

**Issue by kevinmarks** [tommorris/mf2py#38]
See https://github.com/microformats/tests/blob/master/tests/microformats-v2/h-event/time.html

**Comment by kylewm** [comment]
addressed here

https://github.com/kylewm/mf2py/commit/347d3c0503bec4d4003b3e3cdedf057b3b37c5cd

**Comment by kylewm** [comment]
fixed in b81a950b39ead178607def82ee59815f3f425fd8
