### ISSUE TITLE
Needs to parse dt- properties

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#4]
---------------------------------------
- Bitbucket: https://bitbucket.org/tommorris/mf2py/issue/2
- Originally Reported By: [Tom Morris](http://bitbucket.org/tommorris)
- Originally Created At: 2013-11-07T00:36:21.282

**Comment by kylewm** [comment]
initially added 2014-02-17 in c2f8ca489d33ea8faaa8ba0da5f2125707c5927a
