### ISSUE TITLE
Publish a 1.0.0

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#53]
I'm definitely not a semver snob, but I've been thinking about this a bit.

![dont-use-this-module](https://cloud.githubusercontent.com/assets/950127/10011259/611ed6c4-60ac-11e5-9894-42b139eb4116.png)

mf2py isn't perfect, but I think it's safe for general consumption and the public API is going to be relatively stable. Any thoughts?

**Comment by tommorris** [comment]
Seems reasonable. Pinging @kevinmarks, @kartikprabhu, @tantek to see if there's any reason we can't cut a 1.0.0 release.

**Comment by kartikprabhu** [comment]
+1 don't see any major improvement that is needed. mf2py is very usable.

**Comment by kevinmarks** [comment]
Should we do another review of the general mf2 tests first and get them to
a passing state?

**Comment by kylewm** [comment]
Maybe. My impression is that we're a long way toward passing all of the tests, with some major hurdles before we can get there (e.g. standardizing or ignoring whitespace). The tests do not always agree with the spec, and getting them changed is a long process.

**Comment by kartikprabhu** [comment]
yes. afaik there aren't any tests which are standardised specially for datetime formats, whitespaces etc...

**Comment by tommorris** [comment]
I'm leaning towards @kylewm's view - not passing all the tests in the compatibility suite doesn't mean that mf2py isn't currently useable. That's the only measure for cutting a 1.0 release and mf2py has attained that level. I don't see major changes to the public facing API.

Improvements to our test coverage are a nice thing to have. If we change mf2py's behaviour for test completeness, then we should release a new point release.

I'm going to say we've probably reached a rough consensus that 1.0.0 is ready to go. I'll try and release a new version later on today, unless @kylewm beats me to it. ;-)

**Comment by kylewm** [comment]
woohoo thanks! :tada:
