### ISSUE TITLE
add optional parameter to select an HTML parser

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#54]
newer versions of BS4 have started warning

> UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
>
>To get rid of this warning, change this:
>
> BeautifulSoup([your markup])
>
>to this:
>
> BeautifulSoup([your markup], "html5lib")

my preference is to add an optional parameter to `mf2py.parse` and `mf2py.Parser` that passes through to the BeautifulSoup constructor (I'd call it `html_parser`). Acceptable values from [the docs](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#specifying-the-parser-to-use) would be (generic) “html”, “xml”, “html5”, or (specific) “lxml”, “html5lib”, “html.parser”

**Comment by kylewm** [comment]
This + documentation would help with issue #36 too

**Comment by kylewm** [comment]
Last time I proposed this, @kartikprabhu didn't like the idea of exposing BeautifulSoup4-specific stuff through the mf2py API, which I still think is totally valid. But I'm not sure how else to solve this.

**Comment by snarfed** [comment]
the parsers have noticeably different behavior? so the goal here is to choose a parser explicitly so that different environments don't behave differently?

(sorry, i tend to be willfully ignorant of this stuff. :/)

**Comment by kartikprabhu** [comment]
@snarfed yes the parsers have pretty different behaviours. For example, html5lib parser ignores the ``<noscript>`` tag while lxml parses it. But I don't know if mf2 parsing is supposed to parse ``<noscript >`` see: http://microformats.org//wiki/microformats2-parsing-issues#Noscript_skip.2Fparse

**Comment by kevinmarks** [comment]
hit an issue today with a page of tantek's that used h-card in <dd> and it nested the second one, whihc implies xmlish behaviour rather than html5:

http://www.unmung.com/mf2?url=http%3A%2F%2Fwww.w3.org/TR/css3-ui/

worth extracting into a testcase?

**Comment by kylewm** [comment]
> so the goal here is to choose a parser explicitly

to be clear, I don't want to force html5lib or lxml on everyone. I just want to add an optional parameter so callers can choose one explicitly if they want to (to avoid getting the annoying BS4 warning message message if nothing else).

**Comment by kartikprabhu** [comment]
I was opposed to this initially since we would be adding dependency on BS4 (what if we changed parsers later) but, I think we can do the following. Allow for an optional parameter called ``parser``. If the parameter is one of the allowed parsers for whatever we are using internally (currently BS4) then pass it on; else don't pass the parameter at all and let the default one be used.

BS4 is nice about this. If you ask for a parser that is not installed it will simply ignore that so we should be safe.

**Comment by kylewm** [comment]
@kevinmarks ha yeah that's definitely interpreted differently between html5lib and lxml. that'd make a good test case for this parameter in particular

**Comment by kylewm** [comment]
> BS4 is nice about this. If you ask for a parser that is not installed it will simply ignore that so we should be safe.

Coincidentally I just tried this and got an exception (just FYI)

```python
>>> soup = bs4.BeautifulSoup(r.text, features='lxml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kmahan/projects/bridgy/local/local/lib/python2.7/site-packages/bs4/__init__.py", line 152, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by kartikprabhu** [comment]
@kylewm that is odd because the documention claims "If you don’t have an appropriate parser installed, Beautiful Soup will ignore your request and pick a different parser."

can you try ``BeautifulSoup("<a></p>", "lxml")`` instead ?

**Comment by kylewm** [comment]
Same
