### ISSUE TITLE
send custom User-Agent header

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#55]
Many Wordpress installations block the default User-Agent "python-requests". Currently the work-around is to fetch the resource yourself and then pass it to mf2py using the `doc=` parameter. This is not terrible.

If we care to improve it, we could define a custom User-Agent for mf2py `mf2py/version (https://github.com/tommorris/mf2py)` or add an optional parameter to `mf2py.parse` and `mf2py.Parse` to set custom request headers.

**Comment by tommorris** [comment]
We'll roll this into the next release.

**Comment by kylewm** [comment]
Oh funny, I didn't realize useragent had already been defined. It looks like it wasn't being used anywhere though :P I added it to the `requests.get` call and a test.

And I think I fixed the chicken/egg problem with VERSION too, but Travis-CI is running super slow, so it might be a while before we know for sure.
