### ISSUE TITLE
mf1 backward compatibility bug on wordpress oriental theme

### ISSUE THREAD

**Issue by snarfed** [tommorris/mf2py#56]
first discovered in snarfed/bridgy#563. related: #10, kartikprabhu/mf2py#45.

> ooh, actually, mf2py parses this way differently from php-mf2 (above)! cc @kartikprabhu @kylewm. here are the [two](https://brid.gy/log?start_time=1449195955&key=aglzfmJyaWQtZ3lyRwsSDVB1Ymxpc2hlZFBhZ2UiIGh0dHA6Ly9sb3ZlaXN3aG93ZWFyZS5jb20vP3A9NTc3DAsSB1B1Ymxpc2gYgICAgICumQoM) [logs](https://brid.gy/log?start_time=1449195955&key=aglzfmJyaWQtZ3lyRwsSDVB1Ymxpc2hlZFBhZ2UiIGh0dHA6Ly9sb3ZlaXN3aG93ZWFyZS5jb20vP3A9NTc3DAsSB1B1Ymxpc2gYgICAgICumQoM). the parsed mf2 doesn't actually have `entry["properties"]["content"]` at all, just `entry["name"]`, which looks like it matches php-mf2's.
> 
> ```json
> {"items": [{
>   "type": ["h-entry"],
>   "properties": {
>     "name": ["New person-tag test\n\r\n\t\t\tPosted on December 4, 2015 by BrynLove \n\n\nWhen at first you don\u2019t like the way it looks, bugTantek \u00c7elik(t,f) and Ryan Barret(t).\n\n\r\n\t\tThis entry was posted in Uncategorized."]
>   },
>   ...
> }
> ```
> 
> here's the HTML:
> ```html
> <article id="post-552" class="post-552 post type-post status-publish format-standard hentry category-uncategorized kind-">
>   <header class="entry-header">
>     <h1 class="entry-title">Person-tag experiment</h1>
>         <div class="entry-meta">
>       Posted on <a href="http://loveiswhoweare.com/?p=552" title="7:43 pm" rel="bookmark"><time class="entry-date" datetime="2015-12-03T19:43:59+00:00" pubdate>December 3, 2015</time></a><span class="byline"> by <span class="author vcard"><a class="url fn n" href="http://loveiswhoweare.com/?author=1" title="View all posts by BrynLove" rel="author">BrynLove</a></span></span>    </div>
>   </header>
> 
>   <div class="entry-content">
>     <p>So this is me tagging <span class="u-category h-card"><a class="u-url p-name" href="http://alexthejourno.com/">Alex</a>(<a class="u-url" href="https://twitter.com/alexthejourno">t</a>,<a class="u-url"
> href="https://www.facebook.com/alex.campbell.usmc">f</a>)</span> and let&#8217;s try something else, by tagging <span class="u-category h-card"><a class="u-url p-name" href="http://tantek.com/">Tantek</a>(<a class="u-url" href="https://twitter.com/t">t</a>,<a class="u-url"
> href="https://www.facebook.com/tantek.celik">f</a>)<br />
> </span></p>
>       </div>
> 
>   <footer class="entry-meta">
>     This entry was posted in <a href="http://loveiswhoweare.com/?cat=1" rel="category">Uncategorized</a>.  </footer>
> </article>
> ```

**Comment by snarfed** [comment]
we may have to recant. mf2py finds the right content, name, and URL when we fetch and parse manually, so something else is triggering this. we'll keep tracking in snarfed/bridgy #563.

**Comment by kylewm** [comment]
Thanks for the report and followup @snarfed!
