### ISSUE TITLE
performance: bs4.find_all is slow

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#63]
Looking into performance a little more. On my laptop, parsing my own homepage takes about 128ms... This seems the right order of magnitude for what @snarfed is seeing in Bridgy (average ~300ms).

 More than 50% of the total CPU time is spent inside calls to `find_all` (pink in the screenshot below). For comparison, only 33% of the time is spent actually parsing HTML by lxml.

![profile](https://cloud.githubusercontent.com/assets/950127/13674449/5d4cd8fe-e692-11e5-979b-25ccf2469cf4.png)

Drilling down into those calls to find_all, it looks like 11% is the backcompat stuff, 13% is just looking for a `<base>` tag, and eye-balling it looks like another ~15% is with recursive=False to traverse the children of the current node.

This seems pretty unreasonable to me -- Traversing an in-memory data structure shouldn't be such a huge cost, and with the possible exception of backcompat, it's not like we're doing sophisticated pattern matching -- usually we are either looking for any tag or a tag with a particular name.

I wonder if it's worth writing some custom traversal code to use possibly cheaper constructs (`.children` or `.contents`) from bs4.

**Comment by kevinmarks** [comment]
Try parsing some pages where backcompat has to do some work too, with lots
of mf1. If there are no mf1 type classes, we shouldn't go into the child
parsing at all.
Eg http://www.katiejohnson.me/whatimthinking.html
http://chocolateandvodka.com/
http://epeus.blogspot.com

**Comment by snarfed** [comment]
thanks for looking into this more, guys!

might also be worth searching BS's mailing list, issues, FAQ, etc to see if they have anything to say.

**Comment by kevinmarks** [comment]
Thinking about this a little more, the problem may be that we area
approaching this the wrong way using BS in the first place. One way or
another, we need to walk the entire parse tree here; by using BS in this
way we may end up walking it multiple times - BS is focused on syntactic
clarity for extracting a few features, not full traversal.
