### ISSUE TITLE
img alt="" blocks implied name property

### ISSUE THREAD

**Issue by kylewm** [tommorris/mf2py#67]
This html

```html
<a class="h-card" href="https://twitter.com/kylewmahan">
  <img src="https://pbs.twimg.com/profile_images/641457114381074432/vUdKopH8.jpg" alt="">
  @kylewmahan
</a>
```
gives

```json

{"items": [{"properties": {"name": [""],
                           "photo": ["https://pbs.twimg.com/profile_images/641457114381074432/vUdKopH8.jpg"],
                           "url": ["https://twitter.com/kylewmahan"]},
            "type": ["h-card"]}],
 "rel-urls": {},
 "rels": {}}
```

Specifically "name" is blank, where I think it should be "@kylewmahan"

**Comment by kylewm** [comment]
This seems to be based on the implied name rule:

> else if .h-x>img:only-child[alt]:not[.h-*] then use that img alt for name

http://microformats.org/wiki/microformats2-parsing#parsing_for_implied_properties

Is &lt;img> considered the only child even if it has a text node sibling? I don't know XML theory well enough here

**Comment by kevinmarks** [comment]
Good question - I think that is a problem with xpath applied to html
@tantek - is there a way to say "take the text too"?
