### ISSUE TITLE
Needs to parse rels/alternates

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#7]
---------------------------------------
- Bitbucket: https://bitbucket.org/tommorris/mf2py/issue/5
- Originally Reported By: [Tom Morris](http://bitbucket.org/tommorris)
- Originally Created At: 2013-11-07T00:37:27.024

**Comment by kylewm** [comment]
added 2014-03-05 in cef5fe9516cf3f2e375ec34b6c9380776979cbed
