### ISSUE TITLE
Need to implement value-class-pattern

### ISSUE THREAD

**Issue by tommorris** [tommorris/mf2py#9]
---------------------------------------
- Bitbucket: https://bitbucket.org/tommorris/mf2py/issue/7
- Originally Reported By: [Tom Morris](http://bitbucket.org/tommorris)
- Originally Created At: 2013-11-07T00:38:22.418

**Comment by kylewm** [comment]
first implemented 2014-03-14 in 84ee351c74de21d650cb1b1da77a692e7b0bceb2
